name: bloop
description: "A funny little reminder app to help you stay productive and take breaks."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  slide_to_act: ^2.0.2
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.40
  flutter_local_notifications: ^18.0.1
  flutter_foreground_task: ^6.1.1
  shared_preferences: ^2.2.3
  timezone: ^0.9.4
  uuid: ^4.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_timezone: ^5.0.1
  google_nav_bar: ^5.0.7
  confetti: ^0.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/scenery/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  # Android adaptive icon (recommended)
  adaptive_icon_background: "#1E1E2E"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
